### ISSUE TITLE
Configure Catch All and Forward

### ISSUE THREAD

**Issue by blackyzero** [louis-lau/DuckyPanel#10]
Hello,

Is that possible to enable Catch All messages for special account or a domain?
And forward sending or receiving to special email address?

Thank you.

**Comment by louis-lau** [comment]
`*@example.com` works as a catch all.

**Comment by blackyzero** [comment]
Got that. Thanks @louis-lau 
And what is Forwarding Limit this case?

**Comment by louis-lau** [comment]
That has nothing to do with DuckyPanel. The forwarder limit is whatever you set as the forwarding limit.

**Comment by blackyzero** [comment]
It seems not working for forwarding feature.
I set * for domain example.com, and specify the target email is my personal email, however there is no email send to my personal email when i am sending from one of account of example.com

I need a copy of all sending and receiving email of all mailboxes of this domain example.com to my specific personal mailbox. Would it be possible?

**Comment by louis-lau** [comment]
Duckypanel is just for administration of WildDuck, You're asking in the wrong repository.

**Comment by blackyzero** [comment]
Ooops ... got it.
Anyway, thanks @louis-lau

**Comment by louis-lau** [comment]
I only now understand what you're asking though. A forwarder only forwards inbound mail, not outbound. If you want to store outbound mail you would have to write a custom ZoneMTA plugin.
