### ISSUE TITLE
proxying to location different than "/"

### ISSUE THREAD

**Issue by DuredhelFinceleb** [louis-lau/DuckyPanel#11]
Hi, 

I want to proxy ducky panel using the nginx installed by the wildduck install script
If I use location '/' it works OK
but evidently I cannot use that since I need '/' for wildduck 
when I tried to use location '/dpanel' I always get 404 for Ducky Panel files
here is the configuration 
```
location /dpanel {
        proxy_http_version 1.1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header HOST $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_pass http://127.0.0.1:3001;
        proxy_redirect off;
    }
```
I've tried with `proxy_redirect / /dpanel/;` but it did not change anything.
I'm used to Apache's ProxyPass / ProxyPassReverse so maybe I'm missing something with Nginx

Anyway I'm not getting to you for help with nginx
I wanted to ask you if there's a parameter telling Ducky Panel to change it's base URL.
So if I set it to "/dpanel/" the generated base href would be "/dpanel/" instead of "/"
I don't mind if I have to rebuild the app (not familiar with Angular but I know you can do that in Nuxt...)

**Comment by louis-lau** [comment]
In the DuckyPanel release files you can change the `base` element in the `index.html`.
```html
<base href="/" /> --> <base href="/dpanel" />
```

If you're using DuckyAPI's integrated server to serve DuckyPanel you won't have this option. The easiest solution is to use a subdomain like dpanel.example.com. This is what I generally do with all applications I deploy. It's easier, and also more secure as different applications won't be sharing same origin.
