### ISSUE TITLE
DNS Check - dkim selector

### ISSUE THREAD

**Issue by DuredhelFinceleb** [louis-lau/DuckyPanel#12]
Hi, 
in my production.env , I've set DEFAULT_DKIM_SELECTOR to dec2020 (this is the selector the install script gave me)
but in the Panel, it still looks for ducky and therefore tells me there's no dkim record
I'm using the panel integrated with DuckyAPI

**Comment by louis-lau** [comment]
`DEFAULT_DKIM_SELECTOR` gets set when adding a domain to DuckyPanel. You probably added the domain to DuckyPanel while that variable was still set to `ducky`. So it changed your existing dkim selector to `ducky`.

If you don't want DuckyPanel to enable/alter your dkim automatically you can unset that configuration variable.

If you want `dec2020` as your dkim selector you can just edit it in domains in DuckyPanel. You can also set the selector to whatever you want. As long as it's the same in WildDuck and in your DNS you're good.
