### ISSUE TITLE
DNS Check - spf record validity

### ISSUE THREAD

**Issue by DuredhelFinceleb** [louis-lau/DuckyPanel#13]
Hi,

My SPF record is the one suggested by the install script:
v=spf1 a:mail.mydomain.com a:mydomain.com ip4:aaa.bbb.ccc.ddd ~all

The DNS Check tells me it's not valid and I need a valid one to receive emails
I can receive emails just fine though
Is it OK to dismiss this warning?

**Comment by louis-lau** [comment]
DuckyPanel has no way to know what mx records or spf records are valid in your setup. The DNS check is meant for your customers, clients, colleagues. Not for the server operator. If you want it to suggest and check the correct values, set these lines in your DuckyApi config:
https://github.com/louis-lau/DuckyAPI/blob/d4add6d19a3a9b43fbcf5b3c850c855f7671051f/config/example.env#L37-L44
