### ISSUE TITLE
How to configure?

### ISSUE THREAD

**Issue by ramiroaisen** [louis-lau/DuckyPanel#6]
Hy!
Im trying to get it running but the app is trying to connect to localhost:3000
The server im connecting is in another machine, not localhost
It should instead try to connect to ` //${location.hostname}:3000` i think...
How can i configure it?
PS: I have a DuckyApi instance running on port 3000 already.
Thanks!

**Comment by louis-lau** [comment]
Heya,

Sorry for the late response, it appears I wasn't watching my own repo! 🤦 
I haven't yet implemented any configuration for DuckyPanel, but you can edit the url before building here: 
https://github.com/louis-lau/DuckyPanel/blob/master/src/app/app.module.ts#L67

This will obviously be changed 😁

**Comment by louis-lau** [comment]
Proper configuration support has now been added 😁
