### ISSUE TITLE
Integrate DuckyAPI and DuckPanel into one

### ISSUE THREAD

**Issue by blackyzero** [louis-lau/DuckyPanel#8]
Hello @louis-lau 

Thanks again for great apps and support.

Would it possible to unify both DuckyAPI and DuckyPanel into one tool, and this tool can detect Wildduck mail server and auto config it? of course if the Wildduck is used standard install by automation install script.

I am sure this will make more easy and useful.

and thanks a lot.

**Comment by louis-lau** [comment]
Heya,

I've been thinking about this. The reason I separated them is so you can deploy and scale them separately in production, and I'd like to keep it that way. But this does seem to complicate things for folks less experienced with apis or node.js.

I may add a configuration option to DuckyApi that will make it serve DuckyPanel as well.

**Comment by blackyzero** [comment]
That's great. Hope it would be available soon.
Thank you.

**Comment by louis-lau** [comment]
This has now been implemented, should make it a lot easier to deploy for beginners. 😁
